name: development-environment

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm install
      - run: npm run build

  testing:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: testing
        run: npm run test:coverage

  deploy-development-environment:
    needs: testing
    name: development-env
    runs-on: ubuntu-20.04
    environment:
      name: development
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "Deployed to development environment"
