name: development-environment

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  push:
    branches:
      - master
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: npm install
      - run: npm run build

  testing:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: npm install
      - run: npm run test:coverage

  deploy-development-environment:
    if: github.event.review.state == 'approved'
    needs: testing
    name: development-env
    runs-on: ubuntu-20.04
    environment:
      name: development
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: echo "Deployed to development environment"
