name: comment on a issue and get json

on:
  issues:
    types: [opened]
  workflow_dispatch: {}

jobs:
  comment-with-action:
    runs-on: ubuntu-20.04
    steps:
      - name: modify-issue
        shell: bash
        run: echo "The issue had executed the workflow"

      - name: create comment
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The team will review and work on your issue shortly. Thank you for your contribution!
            Created by [@halvaradop][1]

            [1]: https://github.com/halvaradop
          reactions: "+1"

  get-json:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Get JSON
        id: get-json
        shell: bash
        run: echo "${{ github }}"
