name: comment on a issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-20.04
    steps:
      - name: modify-issue
        shell: bash
        run: echo "The issue had executed the workflow"

      - name: create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The team working on your issue.
            Created by [@halvaradop][1]

            [1]: https://github.com/halvaradop
          reactions: "+1"
