name: pull-request-trigger

on:
  pull_request:
    types: [opened, synchronize, closed]
  pull_request_target:
    types: [opened, synchronize, closed]
  
jobs:
  pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ toJson(github.event.pull_request) }}"

  pull-request-target:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ toJson(github.event.pull_request_target) }}"

  pull-request-merge:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy using pull_requet trigger"

  pull-request-target-merge:
    if: github.event_name == 'pull_request_target' && github.event.pull_request_target.merge == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: get json
      - run: echo "Deploy using pull_request_target trigger"
