name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "1.0.0"

jobs:
  create-new-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
