name: testing

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: init
        run: echo "init testing"

      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: install dependencies
        shell: bash
        run: npm install

      - name: testing repo
        shell: bash
        run: npm run test

      - name: end
        run: echo "end testing"